server:
  port: 5000
  pprof_port: 2702

mysql:
  port: 3306
  account: root
  password: 123456789
  addr: 127.0.0.1

lin:
  cms:
    # 开启行为日志记录（logger）
    loggerEnabled: true
    # access jwt 过期时间，3600s 一个小时
    tokenAccessExpire: 3600
    # refresh jwt 过期时间，2592000s 一个月
    tokenRefreshExpire: 2592000
    # 令牌 secret
    tokenSecret: x88Wf0991079889x8796a0Ac68f9ecJJU17c5Vbe8beod7d8d3e695*4